Repository woowa-techcamp-2022/android-banchan-10, pull requests merged in 2022-08, with the labels that each got.

#44 [FIX] Grid Adapter 수정
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/common/MainGridAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/sidedish/SideDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupDishFragment.kt
  app/src/main/res/layout/fragment_maindish.xml
  app/src/main/res/layout/fragment_soupdish.xml
  app/src/main/res/layout/item_maindish_linear.xml
Labels: 우리같이했어요

#45 [FIX] remote api 호출 및 응답구조 수정
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/remote/dao/DishApi.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/remote/model/DishMain.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/remote/model/DishResponse.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/remote/model/DishSoup.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/remote/repository/DishItemRepositoryImpl.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/remote/DishItemRepository.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/CreateUiDishItemsUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetDishListByThemeUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetSideDishListUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetSoupDishListUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/sidedish/SideDishViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupViewModel.kt
Labels: 우리같이했어요

#55 [FEAT] 장바구니 insert시 cart icon 주황색으로 update
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/model/UiDishItem.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/dialogs/bottomsheet/CartBottomSheetFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupViewModel.kt
  app/src/main/res/layout/fragment_cart_dialog.xml
Labels: 우리같이했어요

#67 [FIX] #60 Local DB구조 전격 수정
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/dao/CartDao.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/dao/DishDao.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/dao/OrderDao.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/dao/RecentlyViewedDao.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/db/FoodRoomDatabase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/model/entity/CartInfo.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/model/entity/LocalDish.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/model/entity/OrderInfo.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/model/entity/RecentlyViewedInfo.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/model/join/Cart.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/model/join/Order.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/model/join/RecentlyViewed.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/CartRepositoryImpl.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/DishRepositoryImpl.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/OrderRepositoryImpl.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/RecentlyViewedRepositoryImpl.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/remote/repository/DishDetailRepositoryImpl.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/di/DatabaseModule.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/di/RepositoryModule.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/model/UiCartJoinItem.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/model/UiRecentlyJoinItem.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/model/UiRecentlyViewItem.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/local/CartRepository.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/local/DishRepository.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/local/OrderRepository.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/local/RecentlyViewedRepository.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/remote/DishDetailRepository.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetAllCartInfoUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetAllRecentlyViewedInfoUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetCartInfoUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetCartWithDetailListUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetJoinUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetThemeDishListUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/InsertCartInfoUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/InsertDishUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/InsertOrderDishUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/InsertOrderInfoUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/MapUiDishItemListUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/MapUiDishItemUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartActivity.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/common/CartViewType.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/dialogs/bottomsheet/CartBottomSheetViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/host/DishViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/host/MainActivity.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/state/UiLocalState.kt
Labels: bug

#69 [FIX] 기획전 수평 스크롤 수정
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/common/NestedScrollableHost.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionAdapter.kt
  app/src/main/res/layout/item_exhibition.xml
Labels: bug, 우리같이했어요

#76 [FIX] insert recently viewed 인텐트 수신법, api, db 저장호출부 변경
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/InsertRecentlyUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailActivity.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/host/DishViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupDishFragment.kt
Labels: 우리같이했어요

#101 [FIX] 패키지, 바텀시트 인터페이스, 아이템 데코레이터 수정
  app/src/main/java/com/woowahan/android10/deliverbanchan/DbQueryWorkManager.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/background/CartItemsDbWorker.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/background/OneTimeRequestBuilder.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/dao/CartDao.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/CartRepositoryImpl.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/local/CartRepository.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/InsertAndDeleteCartItemsUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/base/BaseFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartActivity.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/complete/CartDeliveryCompleteFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/complete/adapter/CartDeliveryBodyAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/complete/adapter/CartDeliveryBottomItemAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/complete/adapter/CartDeliveryFooterAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/complete/adapter/CartDeliveryTopAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/main/CartMainFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/main/adapter/CartDishTopBodyAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/main/adapter/CartOrderInfoBottomBodyAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/main/adapter/CartRecentViewedFooterAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/main/adapter/CartSelectHeaderAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/recent/RecentViewedFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/recent/adapter/RecentPagingAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/recent/adapter/RecentViewedVerticalAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/common/OnDishItemClickListener.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/common/OrderListVerticalDecoration.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/common/decorator/GridSpanCountTwoDecorator.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailActivity.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/dialogs/dialog/CartDialogFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/common/MainGridAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/sidedish/SideDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/view/adapter/SortSpinnerAdapter.kt
  app/src/main/res/layout/fragment_sidedish.xml
  app/src/main/res/layout/fragment_soupdish.xml
  app/src/main/res/layout/item_recent_viewed.xml
  app/src/main/res/layout/item_soup.xml
Labels: bug, 우리같이했어요

#118 [FIX] 주문화면과 오더 상세화면의 UI동일로 인한 동일 어댑터 사용
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/dao/OrderDao.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/model/join/Order.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/model/UiCartOrderDishJoinItem.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/model/UiOrderInfo.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/model/UiOrderListItem.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetAllOrderJoinListUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetJoinUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartActivity.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/complete/CartDeliveryCompleteFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/complete/adapter/DeliveryBodyAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/complete/adapter/DeliveryBottomItemAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/complete/adapter/DeliveryFooterAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/complete/adapter/DeliveryTopAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/main/CartMainFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/main/adapter/CartDishTopBodyAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/model/UiCartCompleteHeader.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/common/OrderRequestCode.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/host/MainActivity.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/OrderViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/orderlist/OrderListAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/orderlist/OrderListFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/orderlistdetail/OrderDetailAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/orderlistdetail/OrderDetailFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/orderlistdetail/OrderInfoAdapter.kt
  app/src/main/res/layout/fragment_order_detail.xml
  app/src/main/res/layout/item_cart_dish_top_body.xml
  app/src/main/res/layout/item_cart_order_complete_body.xml
  app/src/main/res/layout/item_cart_order_complete_body_item.xml
  app/src/main/res/layout/item_order_list.xml
Labels: 우리같이했어요

#119 [FIX] detail usecase 최적화
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/model/entity/CartInfo.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/model/UiDetailInfo.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/CreateUiDetailInfoUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetDetailDishUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetJoinUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailActivity.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/state/DetailUiState.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/state/UiDetailState.kt
Labels: 우리같이했어요

#130 [FEAT] #129 Application 레벨의 코루틴 스코프 정의
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/woowahan/android10/deliverbanchan/BanChanApplication.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/GlobalApplication.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartViewModel.kt
Labels: 우리같이했어요

#131 [ FEAT] 주문화면에서 노티피케이션 이벤트 및 화면회전 대응
  app/src/main/java/com/woowahan/android10/deliverbanchan/background/DeliveryReceiver.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/main/CartMainFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/OrderActivity.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/OrderViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/orderlist/OrderListFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/orderlistdetail/OrderDetailFragment.kt
  app/src/main/res/values/strings.xml
Labels: bug, 우리같이했어요

#134 [FEAT] 스플래시 화면 개발
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/ic_banchan-playstore.png
  app/src/main/java/com/woowahan/android10/deliverbanchan/background/DeliveryReceiver.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/main/CartMainFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/host/DishViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/host/MainActivity.kt
  app/src/main/res/layout/item_detail_section_image.xml
  app/src/main/res/layout/item_detail_thumb_image.xml
  app/src/main/res/mipmap-anydpi-v26/ic_banchan.xml
  app/src/main/res/mipmap-anydpi-v26/ic_banchan_round.xml
  app/src/main/res/mipmap-hdpi/ic_banchan.png
  app/src/main/res/mipmap-hdpi/ic_banchan_foreground.png
  app/src/main/res/mipmap-hdpi/ic_banchan_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_banchan.png
  app/src/main/res/mipmap-mdpi/ic_banchan_foreground.png
  app/src/main/res/mipmap-mdpi/ic_banchan_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_banchan.png
  app/src/main/res/mipmap-xhdpi/ic_banchan_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_banchan_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_banchan.png
  app/src/main/res/mipmap-xxhdpi/ic_banchan_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_banchan_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_banchan.png
  app/src/main/res/mipmap-xxxhdpi/ic_banchan_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_banchan_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/ic_banchan_background.xml
  app/src/main/res/values/themes.xml
  buildSrc/src/main/kotlin/woowahan/android10/deliverbanchan/Dependencies.kt
Labels: 우리같이했어요

#135 [FIX] 유즈케이스 정리 및 바텀시트 주문로직 업데이트
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/woowahan/android10/deliverbanchan/background/DeliveryReceiver.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/remote/repository/DishDetailRepositoryImpl.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/remote/DishDetailRepository.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/CartUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/CreateUiDishItemsUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/CreateUiExhibitionItemsUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/DeleteCartInfoByHashListUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/DeleteCartInfoByHashUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetAllCartInfoHashSetUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetAllCartInfoUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetAllRecentViewedInfoUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetCartInfoUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetDetailDishUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetDishListByThemeUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetExhibitionListUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetThemeDishListUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetUiExhibitionItemsUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/InsertAndDeleteCartItemsUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/InsertLocalDishAndRecentUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/InsertLocalDishUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/InsertOrderInfoUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/InsertVarArgOrderInfoUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/IsExistCartInfoUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/MapDishItemListToUiDishItemListUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/MapUiDishItemListUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/MapUiDishItemUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/UpdateCartChecked.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/recent/RecentViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/common/BindingAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/dialogs/bottomsheet/CartBottomSheetViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/host/DishViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/sidedish/SideDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/OrderViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/view/adapter/SortSpinnerAdapter.kt
  app/src/main/res/values/strings.xml
Labels: 우리같이했어요

#136 [FIX] UiState Sealed Class하나로 통일 진행
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/model/UiOrderListItem.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/main/CartMainFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailActivity.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/sidedish/SideDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/sidedish/SideDishViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/OrderViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/orderlist/OrderListAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/orderlist/OrderListFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/state/ExhibitionUiState.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/state/UiDetailState.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/state/UiLocalState.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/state/UiState.kt
  app/src/main/res/layout/item_order_list.xml
Labels: 우리같이했어요

#137 [FIX] 아키텍처 구조 수정 및 Api Request 응답구조 수정
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/CartRepositoryImpl.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/remote/mapper/UiMapper.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/remote/model/response/BaseResult.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/remote/repository/DishDetailRepositoryImpl.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/remote/repository/DishItemRepositoryImpl.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/model/response/BaseResult.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/remote/DishDetailRepository.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/remote/DishItemRepository.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetDetailDishUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetThemeDishListUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetUiExhibitionItemsUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/MapDishItemListToUiDishItemListUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/main/CartMainFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailActivity.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/sidedish/SideDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/sidedish/SideDishViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/OrderViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/orderlist/OrderListFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/state/UiState.kt
Labels: 우리같이했어요

#141 [FEAT] UI State 통일화 및 레이어간 의존성 문제 해결
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/woowahan/android10/deliverbanchan/background/CartItemsDbWorker.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/mapper/DomainMapper.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/mapper/EntityMapper.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/CartRepositoryImpl.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/DishRepositoryImpl.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/OrderRepositoryImpl.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/RecentViewedRepositoryImpl.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/remote/mapper/ApiMapper.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/remote/repository/DishDetailRepositoryImpl.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/remote/repository/DishItemRepositoryImpl.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/model/TempOrder.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/model/UiBottomSheet.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/local/CartRepository.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/local/DishRepository.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/local/OrderRepository.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/local/RecentViewedRepository.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/CartUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/InsertCartInfoUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/InsertLocalDishAndRecentUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/InsertLocalDishUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartActivity.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/dialogs/bottomsheet/CartBottomSheetViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/host/DishViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/host/MainActivity.kt
Labels: 우리같이했어요

#142 [FIX] fragment의 lifecycle 동안 flow collect 수행
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/complete/CartDeliveryCompleteFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/main/CartMainFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/dialogs/bottomsheet/CartBottomSheetFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/sidedish/SideDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/orderlist/OrderListFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/orderlistdetail/OrderDetailFragment.kt
Labels: 우리같이했어요

#143 [FIX] 바인딩 어댑터 익스텐션 타입 별로 분리
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/common/BindingAdapterOrder.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/common/binding/ImageButtonBindingAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/common/binding/ImageViewBindingAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/common/binding/TextViewBindingAdapter.kt
Labels: 우리같이했어요

#144 [FEAT] 카트 액티비티 백스택 관리
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/CartActivity.kt
Labels: 우리같이했어요

#148 [FEAT] detail error loading layout
  app/src/main/java/com/woowahan/android10/deliverbanchan/di/DishApiModule.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailActivity.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/exhibition/ExhibitionFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/sidedish/SideDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupDishFragment.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_exhibition.xml
  app/src/main/res/layout/fragment_maindish.xml
  app/src/main/res/layout/fragment_sidedish.xml
  app/src/main/res/layout/fragment_soupdish.xml
  app/src/main/res/layout/layout_error_screen.xml
  app/src/main/res/values/strings.xml
Labels: 우리같이했어요

#149 [FIX] 메인, 국물, 반찬 리스트 sorting 후 스크롤 내려가는 현상 해결 방법 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/common/ext/ListAdapterExtension.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/maindish/MainDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/sidedish/SideDishFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/soupdish/SoupDishFragment.kt
Labels: 우리같이했어요

#170 Fix/recent data not change
  .idea/deploymentTargetDropDown.xml
  app/src/androidTest/java/com/woowahan/android10/deliverbanchan/data/local/dao/CartDaoTest.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/BanChanApplication.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/dao/CartDao.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/dao/RecentViewedDao.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/mapper/DomainMapper.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/model/entity/RecentViewedInfo.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/model/join/RecentViewed.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/data/local/repository/RecentViewedRepositoryImpl.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/repository/local/RecentViewedRepository.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/GetAllRecentJoinPagerUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/InsertLocalDishAndRecentUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/domain/usecase/RecentUseCase.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/host/CartActivity.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/main/CartMainFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/recent/RecentViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/recent/RecentViewedFragment.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/recent/adapter/RecentViewedVerticalAdapter.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/cart/viewmodel/CartViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/detail/DetailViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/dialogs/bottomsheet/CartBottomSheetViewModel.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/main/host/MainActivity.kt
  app/src/main/java/com/woowahan/android10/deliverbanchan/presentation/order/viewmodel/OrderViewModel.kt
  app/src/main/res/layout/fragment_order_list.xml
Labels: bug
